'use client'

import { Download } from "lucide-react";
import { Button } from "../ui/button";

export default function DownloadSummaryButton({
    title,
    summaryText,
    fileName,
    createdAt,
} : {
    title: string,
    summaryText: string,
    fileName: string,
    createdAt: string,
}) {
    const handleDownload = () => {
        const summaryContent = `# ${title}
Generated Summary
Generated on: ${new Date(createdAt).toLocaleString()}
        
${summaryText}

Original File: ${fileName}
Generated by Lexora
`;

        const blob = new Blob([summaryContent], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `Summary-${title.replace(/[^a-z0-9]/gi, '_')}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    }

    return (
        <Button 
            onClick={handleDownload}
            size="sm"
            className="h-9 bg-linear-to-r from-gray-700 via-gray-800 to-gray-900 text-rose-50 hover:text-rose-700 hover:from-rose-100
            hover:via-rose-200 hover:to-rose-300 transition-all duration-300 ease-in-out"
        >
            <Download className="h-4 w-4 mr-1" />
            Download Summary
        </Button>
    );
}